name = "MyJuliaLib"
uuid = "45fc42ce-9dc1-40eb-86da-0be8acd15afa"
authors = ["Wassim Kassem"]
version = "1.0.0-DEV"

[compat]
julia = "1"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
